### ISSUE TITLE
without mutatons graphiql fails to load schema docs

### ISSUE THREAD

**Issue by NikkyAI** [pgutkowski/KGraphQL#17]
i am using KGraphQL very similar to tihis sample app https://github.com/adavis/ufo-sightings-api
except i want to have a unmodifiable dataset, so removed all mutations

when loading graphiql this error gets printed
```
Error: Mutation fields must be an object with field names as keys or a function which returns such an object.
    at invariant (http://cdn.jsdelivr.net/npm/graphiql@0.11.2/graphiql.js:24809:11)
    at defineFieldMap (http://cdn.jsdelivr.net/npm/graphiql@0.11.2/graphiql.js:28078:27)
    at GraphQLObjectType.getFields (http://cdn.jsdelivr.net/npm/graphiql@0.11.2/graphiql.js:28035:44)
    at typeMapReducer (http://cdn.jsdelivr.net/npm/graphiql@0.11.2/graphiql.js:29752:25)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (http://cdn.jsdelivr.net/npm/graphiql@0.11.2/graphiql.js:29641:34)
    at buildClientSchema (http://cdn.jsdelivr.net/npm/graphiql@0.11.2/graphiql.js:31049:10)
    at http://cdn.jsdelivr.net/npm/graphiql@0.11.2/graphiql.js:2131:55
```

and when i add the mutations back in like this 

```kt
mutation("addNothing") {
    description = "does nothing"

    resolver { input: String -> { println(input)}/**/ }
}
```

it will error with somethoing about the return value of the resulver in the mutation declaration

```
Caused by: org.koin.error.BeanInstanceCreationException: Can't create bean Bean[class=moe.nikky.curseproxy.graphql.AppSchema] due to error :
	com.github.pgutkowski.kgraphql.schema.SchemaException: Generic types are not supported by GraphQL, found () -> kotlin.Unit
```

the introspection query used seems to be 
```
 query IntrospectionQuery {
    __schema {
      queryType { name }
      mutationType { name }
      subscriptionType { name }
      types {
        ...FullType
      }
      directives {
        name
        description
        locations
        args {
          ...InputValue
        }
      }
    }
  }

  fragment FullType on __Type {
    kind
    name
    description
    fields(includeDeprecated: true) {
      name
      description
      args {
        ...InputValue
      }
      type {
        ...TypeRef
      }
      isDeprecated
      deprecationReason
    }
    inputFields {
      ...InputValue
    }
    interfaces {
      ...TypeRef
    }
    enumValues(includeDeprecated: true) {
      name
      description
      isDeprecated
      deprecationReason
    }
    possibleTypes {
      ...TypeRef
    }
  }

  fragment InputValue on __InputValue {
    name
    description
    type { ...TypeRef }
    defaultValue
  }

  fragment TypeRef on __Type {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
                ofType {
                  kind
                  name
                }
              }
            }
          }
        }
      }
    }
  }
```

**Comment by NikkyAI** [comment]
got it to work by registering a dummy mutation that does nothing
```
 mutation("doNothing") {
            description = "Does nothing"
            resolver { a: String ->
                LOG.info("called mutation with $a")
                Dummy()
            }
        }

        type<Dummy> ()
```

**Comment by pgutkowski** [comment]
Hi @NikkyAI please see https://github.com/pgutkowski/KGraphQL/issues/14#issuecomment-374375698. According to GraphQL specification mutation type is optional, but unfortunately Graphiql does not comply to specification in this matter. 

Your solution is right now the best workaround for this problem.
